### ISSUE TITLE
base_import_match - TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by jayo2005** [OCA/server-backend#110]
I get an error installing on Odoo12

`Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 967, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 557, in _button_immediate_function
    function(self)
  File "<decorator-gen-60>", line 2, in button_install
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 394, in button_install
    modules._state_update('to install', ['uninstalled'])
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 373, in _state_update
    module.write({'state': newstate, 'demo': module_demo})
  File "/odoo/odoo-server/addons/website_theme_install/models/ir_module_module.py", line 94, in write
    return super(IrModuleModule, self).write(vals)
  File "/odoo/odoo-server/odoo/models.py", line 3399, in write
    self.recompute()
  File "/odoo/odoo-server/odoo/models.py", line 5312, in recompute
    field, recs = self.env.get_todo()
  File "/odoo/odoo-server/odoo/api.py", line 993, in get_todo
    field = min(self.all.todo, key=self.registry.field_sequence)`

**Comment by jayo2005** [comment]
Reboot of the server sorted it. Great module.
