### ISSUE TITLE
[11.0] base_dav: error blocks "Update Apps List" function

### ISSUE THREAD

**Issue by kwoychesko** [OCA/server-backend#126]
If the base_dav directory exists, when loading Apps the server encounters an error that seems to block the "Update Apps List" function (i.e. none of the other apps in the app-group appear in the Apps list). The final message in the error:
    class Auth(BaseAuth):
TypeError: NoneType takes no arguments

Steps to reproduce:

1. Clone the server-backend repository. 
2. Add the directory to the list of addons in the odoo configuration file.
3. Restart the server.
4. Click the Update Apps List button.
5. Clear the default "Apps" filter and notice that none of the server-backend apps appear in the list.

Full error:

`2021-06-11 11:42:07,548 1 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 348, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 180, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1320, in __call__
    self.load_addons()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1352, in load_addons
    m = __import__('odoo.addons.' + module)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible

  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 3, in <module>

  File "/mnt/extra-addons/server-backend/base_dav/models/__init__.py", line 3, in <module>
    from . import dav_collection
  File "/mnt/extra-addons/server-backend/base_dav/models/dav_collection.py", line 16, in <module>
    from ..radicale.collection import Collection, FileItem, Item
  File "/mnt/extra-addons/server-backend/base_dav/radicale/__init__.py", line 3, in <module>
    from . import auth
  File "/mnt/extra-addons/server-backend/base_dav/radicale/auth.py", line 12, in <module>
    class Auth(BaseAuth):
TypeError: NoneType takes no arguments`

**Comment by kwoychesko** [comment]
NOTE: deleting the base_dav directory and restarting the server fixes the above (i.e. you can then Update Apps List and install other apps in the server-backend group).

**Comment by kwoychesko** [comment]
Update: Sorry -- just missing requirements.
